markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: 腹痛症
url: http://footoredo.github.com
description:
twitter: footo
github: footoredo
gravatar_url: http://en.gravatar.com/userimage/40724226/8f5903d8b878fa3d27c43e56399b6221.jpg?size=200
